CI: azure
CONDA_BUILD_SYSROOT: /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
MACOSX_DEPLOYMENT_TARGET: '11.0'
MACOSX_SDK_VERSION: '11.0'
build_platform: osx-64
c_compiler: clang
c_compiler_version: '16'
c_stdlib: macosx_deployment_target
c_stdlib_version: '11.0'
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: clangxx
extend_keys:
- extend_keys
- ignore_version
- ignore_build_only_deps
- pin_run_as_build
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
macos_machine: arm64-apple-darwin20.0.0
numpy: '1.22'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
python: '3.10'
r_base: '3.5'
target_platform: osx-arm64
